# Generated by Django 5.2.1 on 2025-05-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='analyst',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='analyst',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
