# Generated by Django 5.2.1 on 2025-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysts', '0004_alter_apikey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
