services:
  web:
    build: .
    restart: always
    ports:
      - "7777:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DJANGO_ENV=development
      - SALT=${SALT}
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=pfe_voc
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - AI_URL=${AI_URL}
      - API_KEY=${API_KEY}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pfe_voc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  static_volume:
  media_volume:

# Production configuration
# To use this configuration, run:
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
