# Generated by Django 5.2.1 on 2025-05-18 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vulnerabilities', '0003_alter_vulnerability_options_vulnerability_cve_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('asset_criticality', models.IntegerField()),
                ('state', models.CharField(default='open', max_length=100)),
                ('asset_true_risk_score', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
                ('vulnerabilities', models.ManyToManyField(related_name='assets', to='vulnerabilities.vulnerability')),
            ],
        ),
    ]
