# Generated by Django 5.2.1 on 2025-05-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_exposure',
            field=models.BooleanField(default=True, help_text='If True, exposure value is 1, if False, exposure value is 0.5'),
        ),
    ]
