# Generated by Django 5.2.1 on 2025-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_asset_exposure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_exposure',
            field=models.BooleanField(default=False, help_text='If True (1), the asset is publicly exposed. If False (0), the asset is not publicly exposed.'),
        ),
    ]
