# Generated by Django 5.2.1 on 2025-05-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cve_chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnsiblePlaybook',
        ),
    ]
