# Generated by Django 5.2.1 on 2025-06-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analystfile',
            old_name='type',
            new_name='file_type',
        ),
    ]
