# Generated by Django 5.2.1 on 2025-05-15 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerabilityID', models.IntegerField(unique=True)),
                ('vulnerabilityName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info')], max_length=20)),
                ('cvssScore', models.FloatField()),
                ('affectedAsset', models.CharField(max_length=255)),
                ('remediation', models.TextField()),
                ('epss', models.CharField(blank=True, max_length=50, null=True)),
                ('discoveredDate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['-cvssScore', 'discoveredDate'],
            },
        ),
    ]
